export const PROGRAM_SUBJECTS: Record<string, string[]> = {
  "CIMP": [
    "CIMP ENG4U",
    "CIMP ENG4C",
    "CIMP Functions",
    "CIMP Calculus",
    "CIMP Data Management",
    "CIMP Biology",
    "CIMP Chemistry",
    "CIMP Physics",
    "CIMP Accounting",
    "CIMP International Business",
    "CIMP Business Leadership",
    "CIMP Challenge And Change In Society",
    "CIMP History",
    "CIMP Families In Canada",
    "CIMP Psychology",
    "CIMP Kinesiology",
    "CIMP Computer Science",
    "CIMP Communications Technology",
    "CIMP World Issues: A Geographic Analysis",
    "CIMP Analysing Current Economic Issues",
  ],
  "A-Level": [
    "A-Level Biology",
    "A-Level Chemistry",
    "A-Level Physics",
    "A-Level Mathematics",
    "A-Level Further Mathematics",
    "A-Level Accounting",
    "A-Level Economics",
    "A-Level History",
    "A-Level Law",
    "A-Level Literature in English",
    "A-Level Psychology",
    "A-Level Computer Science",
  ],
  "AUSMAT": [
    "AUSMAT English",
    "AUSMAT English as an Additional Language",
    "AUSMAT Mathematics Applications",
    "AUSMAT Mathematics Methods",
    "AUSMAT Mathematics Specialist",
    "AUSMAT Chemistry",
    "AUSMAT Human Biology",
    "AUSMAT Physics",
    "AUSMAT Accounting & Finance",
    "AUSMAT Business Management & Enterprise",
    "AUSMAT Economics",
    "AUSMAT Psychology",
    "AUSMAT Computer Science",
    "AUSMAT Food Science & Technology",
    "AUSMAT Engineering Studies",
    "AUSMAT Drama",
    "AUSMAT German Studies",
  ],
  "FIA": [
    "FIA Language and Communication",
    "FIA Contemporary Business Mathematics",
    "FIA Critical Thinking Skills",
    "FIA Culture: Arts and Expressions",
    "FIA Introduction to Accounting Techniques",
    "FIA Microeconomics: Concepts and Models",
    "FIA Introduction to Business: Management and Marketing",
    "FIA Introduction to Mass Communication",
    "FIA Introduction to Computer Science",
    "FIA Mathematics for Actuarial Studies",
  ],
  "FIST": [
    "FIST Statistics for Scientists",
    "FIST ICT Application Skills",
    "FIST Basic Computer Concept",
    "FIST Biology 1: Introduction to Biology",
    "FIST Chemistry 1: Basic Chemistry",
    "FIST Physics 1: Principles of Mechanical Science",
  ],
}